[package]
name = "u128-b62"
version = "0.1.0"
edition = "2024"

[dependencies]
phf = { version = "^0.12", features = ["macros"] }

[dev-dependencies]
ulid = { version = "^1.2.1", features = ["uuid"] }
uuid = { version = "1.9.1", features = ["v4", "fast-rng", "serde"] }
